### ISSUE TITLE
AutoCompleteTextFieldState not disposing

### ISSUE THREAD

**Issue by isaacdov2** [felixlucien/flutter-autocomplete-textfield#60]
1) Navigation is Popped while autocomplete is in focus with a list of items being displayed and no item is selected.
2) When the ensuing Navigation screen is popped, the following exception is thrown.

Both Widgets use which create back button at the top:
return new Scaffold(
      appBar: AppBar(
        title: Text("Title"),
      ),
      body: ....

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
setState() called after dispose(): AutoCompleteTextFieldState<Constant>#0a15a(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1105:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1140:6)
#2      AutoCompleteTextFieldState.updateOverlay.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:autocomplete_textfield/autocomplete_textfield.dart:322:37)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
...

**Comment by jovanovski** [comment]
Same issue here!
